### ISSUE TITLE
[1.18.2, Forge] Chat formatting not synced

### ISSUE THREAD

**Issue by HonzaVinCZ** [abc123me/BetterForgeChat#5]
Chat formatting seems to not be synced between clients. Meanwhile your own messages are colored, you can't see other's messages colored. Also name format is set without brackets <>, they show up anyway. Permissions were set.
Discord is not provided by this mod.
Forge 40.1.51
BFC 1.2.1
![2022-12-23_17 28 03](https://user-images.githubusercontent.com/29098779/209397905-a7d52e12-cb75-4e03-bdfe-4438adc9e9fb.png)
![318965093_535616798542402_4034631352633972045_n](https://user-images.githubusercontent.com/29098779/209397977-8662031d-6b35-43b5-bee0-671a1dd15543.png)

**Comment by abc123me** [comment]
This is very strange, the brackets shouldn't be showing, and I haven't experienced this issue on my private server (granted I am on a compiled version straight from the dev branch instead of the 1.3 beta but not much has changed).


Are there any other chat modifications you're using? I noticed you're using V1.2.1 of the mod with some discord mod, What is the discord mod?

**Comment by HonzaVinCZ** [comment]
I can try update the mod on our server and test it again once I meet there with my mate. However we are also little outdated with forge right now but I'm waiting for two mods to update so I can release modpack update. May it be because of older forge version? 

Discord mod is https://www.curseforge.com/minecraft/mc-mods/lightmans-discord-integration

**Comment by abc123me** [comment]
I would seriously doubt the forge version really messes with anything, I think it is more likely the discord mod you're using is interfering with the ServerChatEvent the mod uses.

Would have to setup some tests on my private testing server to test it with the discord mod you're using. I currently have little access to my homelab since it's Christmas, I will work on this later and get back to you.

For now though I'd suggest trying without the discord mod to see if the problem still exists, if not then we know that's the issue. If the discord mod is the issue you can use the beta of my mod with discord integration, until (if possible) I am able to fix the incompatibility with your mod, however my version unfortunately lacks the account linking functionality of the mod you're using (the functionality is however being developed).

**Comment by HonzaVinCZ** [comment]
I do use Lightman's because he also has very decent economy mods. With his economy mod, this integration can even list traders with best prices for given item through discord. However I definitely test it without that mod because I had no idea there could be some connection to this problem. 

Just no hurry!
Thank you for your help and definitely let me know what's new on this issue. I do some tests as well and let you know.

Have a nice holidays!

**Comment by HonzaVinCZ** [comment]
Lightman's Discord Integration deleted, server restarted, issue remains, chat still exactly the same.

**Comment by abc123me** [comment]
Unfortunately I cannot replicate your issue, please send your exact mod list:

![image](https://user-images.githubusercontent.com/8075565/209484495-ddc95816-b0fe-4da4-9846-abcfd87968f5.png)

Merry Christmas to you too! I am happy to help, because this is quite the serious issue but unfortunately I can't do much if I can't replicate the issue!

My guess is probably some client-side mod is interfering with the incoming messages

**Comment by HonzaVinCZ** [comment]
Advanced Chimneys
Pollution of the Realms
Alex's Delight
Alex's Mobs
Ambient Environment
Ambient Sounds
AntiXray
AppleSkin
Applied Energistics 2
Architectury
Balm
BendyLib
BetterF3
BiomesOPlenty
BrewinAndChewin
Catalogue
ComputerCraft Tweaked
Crafish Furniture Mod
Citadel
Cloth Config
Configured
ControlEngineering
Controlling
Corpse
Crafting Dead Core
CraftTweaker
CreativeCore
DynamicTrees
DynamicTreesBOP
DynamicTreesPlus
Emotecraft
EnergyControl
Energymeter
EngineersDecor
EntityCulling
EveryComp
FancyMenu
FarmersDelight
FarmersResprite
Farsighted Mobs
Flan (Forge LANd claiming mod)
Forge Endertech
FTB Backups2
FTB Essentials
FTB Library
FTB Ranks
GuardVillagers
HiddenNames
Chipped
ImmersiveEngineering
Immersive Posts
InControl
InventoryProfilesNext
IronChest
ItemPhysics
Jade
JEI
JeiTweaker
JER Integration
JourneyMap
JustEnoughProffesions
JustEnoughResources
Kiwi
Konkrete
Kotlin
LCTech
Lightman's Currency
LoadMyResources
Macaw's Doors
Macaw's Fences
Macaw's Paths
Macaw's Roofs
Macaw's Trapdoors
Macaw's Windows
MouseTweaks
Observable
Optifine H7
Patchouli
Placebo
PlayerAnimationLib
RSGauges
ScalableCatsForce
Selene (Moonlight lib)
SereneSeasons
ServerTabInfo
SimpleLogin
SimplePlanes
SimpleRPC
SmarterFarmers
SoundPhysics
Starlight
TerraBlender
ThisRocks
ToastControl
ToughAsNails
Towns and Towers
Voicechat
WorldEdit
YungsApi
Yungs Better Dungeons
Yungs Better Mineshafts
Yungs Better Strongholds
Yungs Better WichHuts
Yungs Extras

Server Mods:
Lightmans Discord
Connectivity
LuckPerms
BetterForgeChat
WelcomeMessage
FTB Library
FTB Essentials
Login Protection
Spark
CrashUtilities
Block History
VanishMod
Shutdowner

**Comment by abc123me** [comment]
Wow! That's alot, I'm seeing a few that could cause problems, specifically the VanishMod, Login Protection, Connectivity, and WelcomeMessage. Some other clientside stuff could be doing it, but I'd bet this is a mod interference issue. If you can find the mod causing the issue send me it and I might be able to fix it, otherwise I simply don't have the time to test each of these mods individually. 

I would go through each serverside mod first, then the clientside ones, especially clientside mods that do stuff with chat messages.

**Comment by HonzaVinCZ** [comment]
Umm... I downloaded mods from my server FTP and used them on my local server. I boot up the local server and there is no problem... But with exactly the same mods, there is that issue on hosted dedicated server. What the hell is going on. I even use the same forge version, config folder, world config, just everything is copy pasted and it's different. This is pretty difficult one, sorry.

**Comment by ThirtyTwelveNor** [comment]
not a issue with https://www.curseforge.com/minecraft/mc-mods/mc2discord/

**Comment by HonzaVinCZ** [comment]
Can't reproduce anymore.
