### ISSUE TITLE
[1.18.2, Forge] Nicknames cleared after server restart.

### ISSUE THREAD

**Issue by jayden000** [abc123me/BetterForgeChat#8]
Using the built-in nickname commands, the nicknames don't seem to save after a server restart. I can re-log and change my nicknames all fine but as soon as a server restart happens, and the person logs back in after the restart nicknames get cleared. They also seem to be cleared out of the `bfcmod.playerdata` file when: the person logs in after the restart and has no nickname and the server restarts again.

**Comment by jayden000** [comment]
From more testing, it seems to only happen when there is more than one entry in the `bfcmod.playerdata` file with only one entry in the file it acts as expected. After the restart, it seems to clear everything past the first set nickname.

**Comment by abc123me** [comment]
I'll look into this as soon as I can. I have been extremely busy lately (college + running my own business). To be frank, this project doesn't put any food on my table and served it's purpose so it has gone by the wayside for the past month.

Please make sure when the server is stopped it has time to properly save worlds, player data is saved when this occurs, also if possible please give me some server log files, mod list, the bfcmod config file, and finally the result of `/bfcmod info` as this will help me out.

There is a good chance this is down to a mod incompatibility, permissions error, or something similar as my own personal server does not have any issues with the integrated nickname commands ( it also runs an unreleased beta version of the mod, so that could be the difference).

Sidenote, you can use FTB essentials for temporary nickname integration however they won't sync with the integrated nickname integration.

**Comment by jayden000** [comment]
I do indeed give it time to save player data and all as it seems like one nickname saved but the moment there are multiple in the file, it doesn't save the other ones after the server restart. I'll get you a list of mods and the other things you requested. I appreciate you taking a look into this and I completely understand the time and priories aspect. Take your time

**Comment by jayden000** [comment]
[mod list.txt](https://github.com/abc123me/BetterForgeChat/files/10417415/mod.list.txt)
[bfc-info.txt](https://github.com/abc123me/BetterForgeChat/files/10417419/bfc-info.txt)

[bfcmod-common.txt](https://github.com/abc123me/BetterForgeChat/files/10417418/bfcmod-common.txt)

I can also send you a demo and the logs of the server when this happens, privately, if you have another method of contact (Discord, etc)

**Comment by abc123me** [comment]
The bfc-info.txt file is empty, also please include a server log file so I can check for any unusual outputs!

**Comment by jayden000** [comment]
> The bfc-info.txt file is empty, also please include a server log file so I can check for any unusual outputs!

My apologies, did this early in the morning lol
[bfc-info.txt](https://github.com/abc123me/BetterForgeChat/files/10418796/bfc-info.txt)

I will get you a server log file of me setting the nickname on an account that hasn't set a nickname before, stand by.

**Comment by jayden000** [comment]
Here is the server log, just a note upon after shutting down this server and restarting it. The nickname was cleared and not saved from this user.

https://pastebin.com/4Wff1eQ9

Again, if needed, I can show reproduction steps in a video that I can share privately.

**Comment by abc123me** [comment]
I setup a test build using the exact version (V1.2.1) off of CurseForge and cannot replicate this issue using just LuckPerms and the base instance of the mod, this indicates the issue is a mod incompatibility. Please find the offending mod and remove it, please submit the offending mod and I will see if the incompatibility can be fixed. Otherwise this issue will be closed for now.
